baseURL = "https://rachja1.github.io/"
languageCode = "en-us"
title = "Rachel Salamatian"
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[params]
  description = "Academic website of Rachel Salamatian"

  image = "/images/lab_portrait.jpg"
  images = ["images/lab_portrait.jpg"]

  [params.author]
    name = "Rachel Salamatian"
    email = "rajacobs11@gmail.com"

  [params.socialIcons]
    email = "mailto:rachelj97@icloud.com"
    github = "https://github.com/rachja1"
    linkedin = "https://www.linkedin.com/"

[menu]
  [[menu.main]]
    name = "Introduction"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2
  [[menu.main]]
    name = "Teaching & Mentoring"
    url = "/teaching/"
    weight = 3
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
